import React,{useEffect,useState} from "react";
import {View,Text,ScrollView,Pressable,TextInput,Alert,StyleSheet} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Linking from "expo-linking";
import {getSupabasePublicConfig} from "../lib/supabase-config";
import {supabase} from "../lib/supabase";
type Game={id:string,sport:string,title:string,venue:string,time:string,players:number,max:number,joined:boolean};
const seed:Game[]=[{id:"football-1",sport:"⚽",title:"Evening Football",venue:"Central Park · North Meadow",time:"Today · 6:30 PM",players:7,max:10,joined:false},{id:"basketball-1",sport:"🏀",title:"Pickup Basketball",venue:"West 4th Street Courts",time:"Today · 7:00 PM",players:8,max:10,joined:false},{id:"badminton-1",sport:"🏸",title:"Badminton Doubles",venue:"Community Sports Center",time:"Tomorrow · 9:00 AM",players:2,max:4,joined:false},{id:"run-1",sport:"🏃",title:"Easy 5K Run",venue:"Riverside Park",time:"Tomorrow · 7:00 AM",players:4,max:12,joined:false}];
const C={bg:"#0B0F14",card:"#151C25",line:"#263343",text:"#E8ECF1",muted:"#9AA8B8",green:"#00E676"};
export default function Home(){const backend=getSupabasePublicConfig();const [games,setGames]=useState(seed),[tab,setTab]=useState("Explore"),[filter,setFilter]=useState("All"),[q,setQ]=useState(""),[title,setTitle]=useState(""),[venue,setVenue]=useState(""),[sport,setSport]=useState("⚽"),[accountEmail,setAccountEmail]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authBusy,setAuthBusy]=useState(false);
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setAccountEmail(data.session?.user.email??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setAccountEmail(session?.user.email??null));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!supabase)return;let handled=false;const handleAuthRedirect=async(url:string)=>{if(handled)return;const parsed=Linking.parse(url);const params=parsed.queryParams??{};const queryCode=params.code;const code=Array.isArray(queryCode)?queryCode[0]:queryCode;if(typeof code==="string"&&code){handled=true;const {error}=await supabase.auth.exchangeCodeForSession(code);if(error)Alert.alert("Confirmation link",error.message);else Alert.alert("Email confirmed","You are now signed in to KickOff.");return}const hash=url.split("#")[1];if(hash){const hashParams=new URLSearchParams(hash);const accessToken=hashParams.get("access_token");const refreshToken=hashParams.get("refresh_token");if(accessToken&&refreshToken){handled=true;const {error}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(error)Alert.alert("Confirmation link",error.message);else Alert.alert("Email confirmed","You are now signed in to KickOff.");}}};const listener=Linking.addEventListener("url",({url})=>{void handleAuthRedirect(url)});Linking.getInitialURL().then(url=>{if(url)void handleAuthRedirect(url)}).catch(()=>{});return()=>listener.remove()},[]);
useEffect(()=>{AsyncStorage.getItem("kickoff.games.v1").then(v=>{if(v)setGames(JSON.parse(v))}).catch(()=>{})},[]);
const save=(v:Game[])=>{setGames(v);AsyncStorage.setItem("kickoff.games.v1",JSON.stringify(v)).catch(()=>Alert.alert("Storage error"))};
const join=(g:Game)=>{if(!g.joined&&g.players>=g.max){Alert.alert("Game full","This game has reached capacity.");return}save(games.map(x=>x.id===g.id?{...x,joined:!x.joined,players:x.players+(x.joined?-1:1)}:x))};
const list=games.filter(g=>(filter==="All"||g.sport===filter)&&[g.title,g.venue].join(" ").toLowerCase().includes(q.toLowerCase()));
const authenticate=async(mode:"signin"|"signup")=>{if(!supabase)return;if(!email.trim()||password.length<6){Alert.alert("Check your details","Enter a valid email and a password with at least 6 characters.");return}setAuthBusy(true);try{const result=mode==="signin"?await supabase.auth.signInWithPassword({email:email.trim(),password}):await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:Linking.createURL("auth/callback")}});if(result.error)throw result.error;if(mode==="signup"&&!result.data.session)Alert.alert("Check your email","Confirm your email address, then sign in.");}catch(e){Alert.alert("Account error",e instanceof Error?e.message:"Please try again.")}finally{setAuthBusy(false)}};
const signOut=async()=>{if(!supabase)return;setAuthBusy(true);const {error}=await supabase.auth.signOut();setAuthBusy(false);if(error)Alert.alert("Sign out failed",error.message)};
const create=()=>{if(!title.trim()||!venue.trim()){Alert.alert("Missing details","Add a game name and venue.");return}save([{id:"game-"+Date.now(),sport,title:title.trim(),venue:venue.trim(),time:"New · schedule to be confirmed",players:1,max:10,joined:true},...games]);setTitle("");setVenue("");setTab("Explore");Alert.alert("Game created","Saved on this device.")};
return <View style={s.root}><View style={s.header}><View><Text style={s.kicker}>YOUR LOCAL SPORTS COMMUNITY</Text><Text style={s.logo}>Kick<Text style={{color:C.green}}>Off</Text></Text></View><Text style={s.avatar}>K</Text></View>
{tab==="Explore"? <><View style={s.hero}><Text style={s.headline}>Find your next{"\n"}game.</Text><Text style={s.muted}>Good games start with showing up.</Text><View style={s.mode}><View style={s.modeDot}/><Text style={s.modeText}>{backend.configured?"BACKEND CONFIGURED · DEMO DATA":"LOCAL DEMO · SAVED ON THIS DEVICE"}</Text></View><TextInput value={q} onChangeText={setQ} placeholder="⌕  Search sport or location" placeholderTextColor="#718093" style={s.input}/></View><View style={s.filters}>{["All","⚽","🏀","🏸","🏃"].map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[s.pill,filter===x&&s.selected]}><Text style={{color:filter===x?C.green:C.muted,fontWeight:"700"}}>{x}</Text></Pressable>)}</View><ScrollView contentContainerStyle={{padding:18,paddingBottom:100}}><Text style={s.section}>Games near you <Text style={s.muted}>· {list.length}</Text></Text>{list.map(g=><View key={g.id} style={s.card}><View style={s.row}><Text style={s.emoji}>{g.sport}</Text><View style={{flex:1}}><Text style={s.gameTitle}>{g.title}</Text><Text style={s.muted}>{g.venue}</Text></View><Text style={s.open}>OPEN</Text></View><Text style={s.meta}>{g.time} · {g.players}/{g.max} players</Text><View style={s.row}><View style={s.bar}><View style={{height:5,width:(g.players/g.max*100)+"%",backgroundColor:C.green,borderRadius:5}}/></View><Pressable onPress={()=>join(g)} style={[s.button,g.joined&&s.joined]}><Text style={{color:g.joined?C.green:C.bg,fontWeight:"800"}}>{g.joined?"Joined ✓":"Join game"}</Text></Pressable></View></View>)}</ScrollView></>:null}
{tab==="Create"?<ScrollView contentContainerStyle={s.form}><Text style={s.headline}>Make it happen.</Text><Text style={s.muted}>Bring people together for a game.</Text><Text style={s.label}>SPORT</Text><View style={s.filters}>{["⚽","🏀","🏸","🏃"].map(x=><Pressable key={x} onPress={()=>setSport(x)} style={[s.pill,sport===x&&s.selected]}><Text style={{fontSize:20}}>{x}</Text></Pressable>)}</View><Text style={s.label}>GAME NAME</Text><TextInput value={title} onChangeText={setTitle} placeholder="Sunday morning football" placeholderTextColor="#718093" style={s.input}/><Text style={s.label}>VENUE</Text><TextInput value={venue} onChangeText={setVenue} placeholder="Park, court or sports ground" placeholderTextColor="#718093" style={s.input}/><Pressable style={s.create} onPress={create}><Text style={{color:C.bg,fontWeight:"900"}}>Create game →</Text></Pressable><Text style={s.muted}>Demo mode: local device storage only. Shared accounts, bookings and chat are not connected.</Text></ScrollView>:null}
{tab==="My games"?<ScrollView contentContainerStyle={s.form}><Text style={s.headline}>Your games.</Text>{games.filter(g=>g.joined).map(g=><View style={s.card} key={g.id}><Text style={s.gameTitle}>{g.sport} {g.title}</Text><Text style={s.muted}>{g.venue}</Text><Pressable onPress={()=>join(g)}><Text style={{color:"#FF6D3A",marginTop:12,fontWeight:"700"}}>Leave game</Text></Pressable></View>)}{!games.some(g=>g.joined)&&<Text style={s.muted}>No games joined yet.</Text>}</ScrollView>:null}
{tab==="Profile"?<ScrollView contentContainerStyle={s.form}><Text style={s.headline}>Player profile.</Text><View style={s.card}><Text style={s.gameTitle}>Welcome to KickOff</Text>{!supabase?<Text style={s.muted}>Connect a Supabase project using the EXPO_PUBLIC variables to enable accounts. Local demo mode remains available.</Text>:accountEmail?<><Text style={s.muted}>Signed in as {accountEmail}</Text><Pressable disabled={authBusy} onPress={signOut} style={[s.create,{backgroundColor:"#263343"}]}><Text style={{color:C.text,fontWeight:"900"}}>{authBusy?"Please wait…":"Sign out"}</Text></Pressable></>:<><Text style={s.muted}>Sign in or create an account to get started.</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Email address" placeholderTextColor="#718093" style={s.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password (6+ characters)" placeholderTextColor="#718093" style={s.input}/><Pressable disabled={authBusy} onPress={()=>authenticate("signin")} style={s.create}><Text style={{color:C.bg,fontWeight:"900"}}>{authBusy?"Please wait…":"Sign in →"}</Text></Pressable><Pressable disabled={authBusy} onPress={()=>authenticate("signup")} style={[s.create,{backgroundColor:"#263343",marginTop:10}]}><Text style={{color:C.text,fontWeight:"900"}}>Create account</Text></Pressable></>}</View><Text style={s.muted}>Your local demo games are stored on this device and are not synced to your account yet.</Text></ScrollView>:null}
<View style={s.nav}>{[["Explore","⌂"],["My games","▣"],["Create","＋"],["Profile","◉"]].map(([t,i])=><Pressable key={t} onPress={()=>setTab(t)} style={s.navItem}><Text style={{fontSize:21,color:tab===t?C.green:C.muted}}>{i}</Text><Text style={{fontSize:10,color:tab===t?C.green:C.muted,fontWeight:"700"}}>{t}</Text></Pressable>)}</View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.bg,paddingTop:52},header:{paddingHorizontal:20,paddingBottom:14,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},kicker:{fontSize:9,color:C.muted,letterSpacing:1.5,fontWeight:"800"},logo:{fontSize:29,color:C.text,fontWeight:"900"},avatar:{backgroundColor:"#183326",color:C.green,overflow:"hidden",borderRadius:14,padding:10,fontWeight:"900"},hero:{padding:20},headline:{fontSize:38,lineHeight:42,color:C.text,fontWeight:"900",letterSpacing:-1.5},muted:{fontSize:12,color:C.muted,marginTop:6},input:{marginTop:18,backgroundColor:C.card,borderColor:C.line,borderWidth:1,borderRadius:12,padding:14,color:C.text},filters:{flexDirection:"row",gap:8,paddingHorizontal:18,paddingVertical:6},pill:{paddingHorizontal:16,paddingVertical:9,borderRadius:24,borderWidth:1,borderColor:C.line,backgroundColor:C.card},selected:{borderColor:C.green,backgroundColor:"#10271B"},mode:{flexDirection:"row",alignItems:"center",gap:7,alignSelf:"flex-start",marginTop:14,paddingHorizontal:10,paddingVertical:7,borderRadius:20,backgroundColor:"#18231F"},modeDot:{width:6,height:6,borderRadius:3,backgroundColor:C.green},modeText:{fontSize:9,color:C.green,fontWeight:"800",letterSpacing:0.7},section:{fontSize:18,color:C.text,fontWeight:"800",marginBottom:14},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:17,padding:15,marginBottom:12},row:{flexDirection:"row",alignItems:"center",gap:12},emoji:{fontSize:23,backgroundColor:"#202D38",padding:10,borderRadius:12},gameTitle:{fontSize:15,color:C.text,fontWeight:"800"},open:{color:C.green,fontSize:10,fontWeight:"900",backgroundColor:"#10271B",padding:7,borderRadius:6},meta:{fontSize:11,color:C.muted,marginTop:13},bar:{height:5,width:90,backgroundColor:"#303B48",borderRadius:5},button:{backgroundColor:C.green,borderRadius:10,paddingHorizontal:16,paddingVertical:10},joined:{backgroundColor:"#183326",borderWidth:1,borderColor:C.green},nav:{position:"absolute",bottom:0,left:0,right:0,height:76,backgroundColor:"#101720",borderTopWidth:1,borderColor:C.line,flexDirection:"row",justifyContent:"space-around",alignItems:"center",paddingBottom:10},navItem:{alignItems:"center",gap:4,minWidth:60},form:{padding:20,paddingBottom:110},label:{fontSize:10,color:C.muted,fontWeight:"800",letterSpacing:1.5,marginTop:24,marginBottom:8},create:{marginTop:25,backgroundColor:C.green,padding:16,borderRadius:13,alignItems:"center"}});
